### ISSUE TITLE
Exception while installing current git master

### ISSUE THREAD

**Issue by Pastafarianist** [maartenbreddels/ipyvolume#34]
```
$ pip install --user -e .
Obtaining file:///home/user/repos/ipyvolume
Requirement already satisfied: ipywidgets>=6.0.0b5 in /usr/lib/python3.6/site-packages (from ipyvolume==0.4.0a2)
Requirement already satisfied: numpy in /usr/lib/python3.6/site-packages (from ipyvolume==0.4.0a2)
Requirement already satisfied: traittypes in /home/user/.local/lib/python3.6/site-packages (from ipyvolume==0.4.0a2)
Requirement already satisfied: traitlets in /usr/lib/python3.6/site-packages (from ipyvolume==0.4.0a2)
Requirement already satisfied: Pillow in /usr/lib/python3.6/site-packages (from ipyvolume==0.4.0a2)
Requirement already satisfied: pandas in /usr/lib/python3.6/site-packages (from traittypes->ipyvolume==0.4.0a2)
Requirement already satisfied: olefile in /usr/lib/python3.6/site-packages (from Pillow->ipyvolume==0.4.0a2)
Requirement already satisfied: python-dateutil>=2 in /usr/lib/python3.6/site-packages (from pandas->traittypes->ipyvolume==0.4.0a2)
Requirement already satisfied: pytz>=2011k in /usr/lib/python3.6/site-packages (from pandas->traittypes->ipyvolume==0.4.0a2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil>=2->pandas->traittypes->ipyvolume==0.4.0a2)
Installing collected packages: ipyvolume
  Running setup.py develop for ipyvolume
Successfully installed ipyvolume

$ jupyter nbextension install --py --symlink ipyvolume
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbextension", line 6, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 900, in start
    super(NBExtensionApp, self).start()
  File "/usr/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 678, in start
    self.install_extensions()
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 657, in install_extensions
    **kwargs
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 1034, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/home/user/repos/ipyvolume/ipyvolume/__init__.py", line 5, in <module>
    from .volume import *
  File "/home/user/repos/ipyvolume/ipyvolume/volume.py", line 12, in <module>
    from .transferfunction import *
  File "/home/user/repos/ipyvolume/ipyvolume/transferfunction.py", line 40, in <module>
    class TransferFunctionJsBumps(TransferFunction):
TypeError: function() argument 1 must be code, not str
```

**Comment by maartenbreddels** [comment]
Hi,

You need ipywidgets7, try installing the latest alpha from pip ($ pip install ipywidgets~=7.0.0a10), that should work. I'll update setup.py, thanks for the report!

Cheers,

Maarten
